package Parte2;

/**
 *
 * @author sebastian
 */
public class Figuras extends javax.swing.JFrame {

    /**
     * Creates new form Figuras
     */
    public Figuras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        circuloPanel = new javax.swing.JPanel();
        circuloLabel = new javax.swing.JLabel();
        radioInput = new javax.swing.JTextField();
        radioLabel = new javax.swing.JLabel();
        circuloAnsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        circuloTextPane = new javax.swing.JTextPane();
        enviarCirculo = new javax.swing.JButton();
        cuadradoPanel = new javax.swing.JPanel();
        cuadradoLabel1 = new javax.swing.JLabel();
        ladoInput1 = new javax.swing.JTextField();
        ladoLabel1 = new javax.swing.JLabel();
        cuadradoAnsPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CuadradoTextPane = new javax.swing.JTextPane();
        enviarCuadrado = new javax.swing.JButton();
        rectanguloPanel = new javax.swing.JPanel();
        rectanguloLabel = new javax.swing.JLabel();
        baseLabel = new javax.swing.JLabel();
        baseInput = new javax.swing.JTextField();
        alturaLabel = new javax.swing.JLabel();
        alturaInput = new javax.swing.JTextField();
        enviarRectangulo = new javax.swing.JButton();
        rectanguloAnsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectanguloTextPane = new javax.swing.JTextPane();
        rectanguloPanel1 = new javax.swing.JPanel();
        rectanguloLabel1 = new javax.swing.JLabel();
        baseLabel1 = new javax.swing.JLabel();
        baseInput1 = new javax.swing.JTextField();
        alturaLabel1 = new javax.swing.JLabel();
        alturaInput1 = new javax.swing.JTextField();
        enviarTrianguloRectangulo = new javax.swing.JButton();
        rectanguloAnsPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        trianguloRectanguloTextPane = new javax.swing.JTextPane();
        mensajeAns = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setText("Parte 2");

        circuloPanel.setBackground(new java.awt.Color(215, 215, 215));

        circuloLabel.setText("Circulo");

        radioInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInputActionPerformed(evt);
            }
        });

        radioLabel.setText("Radio:");

        jScrollPane2.setViewportView(circuloTextPane);

        javax.swing.GroupLayout circuloAnsPanelLayout = new javax.swing.GroupLayout(circuloAnsPanel);
        circuloAnsPanel.setLayout(circuloAnsPanelLayout);
        circuloAnsPanelLayout.setHorizontalGroup(
            circuloAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circuloAnsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        circuloAnsPanelLayout.setVerticalGroup(
            circuloAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circuloAnsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        enviarCirculo.setText("Enviar");
        enviarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout circuloPanelLayout = new javax.swing.GroupLayout(circuloPanel);
        circuloPanel.setLayout(circuloPanelLayout);
        circuloPanelLayout.setHorizontalGroup(
            circuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circuloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(circuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(circuloLabel)
                    .addGroup(circuloPanelLayout.createSequentialGroup()
                        .addComponent(radioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(circuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enviarCirculo)
                            .addComponent(radioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(circuloAnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        circuloPanelLayout.setVerticalGroup(
            circuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circuloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(circuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(circuloAnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(circuloPanelLayout.createSequentialGroup()
                        .addComponent(circuloLabel)
                        .addGap(18, 18, 18)
                        .addGroup(circuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioLabel))
                        .addGap(18, 18, 18)
                        .addComponent(enviarCirculo)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cuadradoPanel.setBackground(new java.awt.Color(215, 215, 215));

        cuadradoLabel1.setText("Cuadrado");

        ladoInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladoInput1ActionPerformed(evt);
            }
        });

        ladoLabel1.setText("Lado:");

        jScrollPane3.setViewportView(CuadradoTextPane);

        javax.swing.GroupLayout cuadradoAnsPanel1Layout = new javax.swing.GroupLayout(cuadradoAnsPanel1);
        cuadradoAnsPanel1.setLayout(cuadradoAnsPanel1Layout);
        cuadradoAnsPanel1Layout.setHorizontalGroup(
            cuadradoAnsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuadradoAnsPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        cuadradoAnsPanel1Layout.setVerticalGroup(
            cuadradoAnsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuadradoAnsPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        enviarCuadrado.setText("Enviar");
        enviarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadradoPanelLayout = new javax.swing.GroupLayout(cuadradoPanel);
        cuadradoPanel.setLayout(cuadradoPanelLayout);
        cuadradoPanelLayout.setHorizontalGroup(
            cuadradoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadradoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cuadradoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadradoLabel1)
                    .addGroup(cuadradoPanelLayout.createSequentialGroup()
                        .addComponent(ladoLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cuadradoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ladoInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cuadradoPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(enviarCuadrado)))))
                .addGap(36, 36, 36)
                .addComponent(cuadradoAnsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cuadradoPanelLayout.setVerticalGroup(
            cuadradoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadradoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cuadradoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadradoAnsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cuadradoPanelLayout.createSequentialGroup()
                        .addComponent(cuadradoLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(cuadradoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ladoInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ladoLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(enviarCuadrado)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );

        rectanguloPanel.setBackground(new java.awt.Color(215, 215, 215));

        rectanguloLabel.setText("Rectangulo");

        baseLabel.setText("Base:");

        baseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseInputActionPerformed(evt);
            }
        });

        alturaLabel.setText("Altura:");

        alturaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaInputActionPerformed(evt);
            }
        });

        enviarRectangulo.setText("Enviar");
        enviarRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarRectanguloActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(rectanguloTextPane);

        javax.swing.GroupLayout rectanguloAnsPanelLayout = new javax.swing.GroupLayout(rectanguloAnsPanel);
        rectanguloAnsPanel.setLayout(rectanguloAnsPanelLayout);
        rectanguloAnsPanelLayout.setHorizontalGroup(
            rectanguloAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rectanguloAnsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        rectanguloAnsPanelLayout.setVerticalGroup(
            rectanguloAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rectanguloAnsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout rectanguloPanelLayout = new javax.swing.GroupLayout(rectanguloPanel);
        rectanguloPanel.setLayout(rectanguloPanelLayout);
        rectanguloPanelLayout.setHorizontalGroup(
            rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectanguloPanelLayout.createSequentialGroup()
                .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rectanguloPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rectanguloLabel)
                            .addGroup(rectanguloPanelLayout.createSequentialGroup()
                                .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(baseLabel)
                                    .addComponent(alturaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(baseInput, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alturaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(rectanguloPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(enviarRectangulo)))
                .addGap(36, 36, 36)
                .addComponent(rectanguloAnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rectanguloPanelLayout.setVerticalGroup(
            rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectanguloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rectanguloPanelLayout.createSequentialGroup()
                        .addComponent(rectanguloAnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(rectanguloPanelLayout.createSequentialGroup()
                        .addComponent(rectanguloLabel)
                        .addGap(18, 18, 18)
                        .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(baseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baseLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rectanguloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alturaLabel)
                            .addComponent(alturaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(enviarRectangulo)
                        .addGap(23, 23, 23))))
        );

        rectanguloPanel1.setBackground(new java.awt.Color(215, 215, 215));

        rectanguloLabel1.setText("Triangulo Rectangulo");

        baseLabel1.setText("Base:");

        baseInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseInput1ActionPerformed(evt);
            }
        });

        alturaLabel1.setText("Altura:");

        alturaInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaInput1ActionPerformed(evt);
            }
        });

        enviarTrianguloRectangulo.setText("Enviar");
        enviarTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarTrianguloRectanguloActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(trianguloRectanguloTextPane);

        javax.swing.GroupLayout rectanguloAnsPanel1Layout = new javax.swing.GroupLayout(rectanguloAnsPanel1);
        rectanguloAnsPanel1.setLayout(rectanguloAnsPanel1Layout);
        rectanguloAnsPanel1Layout.setHorizontalGroup(
            rectanguloAnsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rectanguloAnsPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        rectanguloAnsPanel1Layout.setVerticalGroup(
            rectanguloAnsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rectanguloAnsPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout rectanguloPanel1Layout = new javax.swing.GroupLayout(rectanguloPanel1);
        rectanguloPanel1.setLayout(rectanguloPanel1Layout);
        rectanguloPanel1Layout.setHorizontalGroup(
            rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectanguloPanel1Layout.createSequentialGroup()
                .addGroup(rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rectanguloPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(baseLabel1)
                            .addComponent(alturaLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alturaInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rectanguloPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(enviarTrianguloRectangulo))
                    .addGroup(rectanguloPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rectanguloLabel1)))
                .addGap(36, 36, 36)
                .addComponent(rectanguloAnsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rectanguloPanel1Layout.setVerticalGroup(
            rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rectanguloPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rectanguloAnsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(rectanguloPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rectanguloLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rectanguloPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaLabel1))
                .addGap(18, 18, 18)
                .addComponent(enviarTrianguloRectangulo)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mensajeAns)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(0, 906, Short.MAX_VALUE))
                            .addComponent(circuloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuadradoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rectanguloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rectanguloPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensajeAns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(circuloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cuadradoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rectanguloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rectanguloPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>                        

    private void radioInputActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void enviarCirculoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        String mensaje;
        double radio,perimetro,area;

        try{
            radio=Double.parseDouble(radioInput.getText());
            area=Math.pow(radio, 2)*Math.PI;
            perimetro=2*radio*Math.PI;
            mensaje="Datos introducidos correctamente";
            mensajeAns.setText(mensaje);
            circuloTextPane.setText("area: "+area+"\n"+"perimetro: "+perimetro);
        }
        catch(Exception e){
            mensaje="Entradas no válidas"+e;
            mensajeAns.setText(mensaje);
        }
    }                                             

    private void baseInputActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void enviarRectanguloActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        String mensaje;
        double base,altura;
        double area,perimetro;

        try{
            base=Double.parseDouble(baseInput.getText());
            altura=Double.parseDouble(alturaInput.getText());
            area=base*altura;
            perimetro=2*base+2*altura;
            mensaje="Datos introducidos correctamente";
            mensajeAns.setText(mensaje);
            rectanguloTextPane.setText("area: "+area+"\n"+"perimetro: "+perimetro);
        }
        catch(Exception e){
            mensaje="Entradas no válidas"+e;
            mensajeAns.setText(mensaje);
        }
    }                                                

    private void ladoInput1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void enviarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        String mensaje;
        double lado;
        double area,perimetro;

        try{
            lado=Double.parseDouble(ladoInput1.getText());
            area=Math.pow(lado, 2);
            perimetro=lado*4;
            mensaje="Datos introducidos correctamente";
            mensajeAns.setText(mensaje);
            CuadradoTextPane.setText("area: "+area+"\n"+"perimetro: "+perimetro);
        }
        catch(Exception e){
            mensaje="Entradas no válidas"+e;
            mensajeAns.setText(mensaje);
        }
    }                                              

    private void alturaInputActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void baseInput1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void alturaInput1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void enviarTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
                // TODO add your handling code here:
        String mensaje,tipoTriangulo;
        double base,altura,area,perimetro,hipotenusa;

        try{
            base=Double.parseDouble(baseInput.getText());
            altura=Double.parseDouble(alturaInput.getText());
            
            area=(base*altura)/2;
            hipotenusa=Math.pow(base, 2)+Math.pow(altura, 2);
            perimetro=base+altura+hipotenusa;
            if ((base==altura) && (base == hipotenusa) && (altura == hipotenusa)){
                tipoTriangulo="Es un triangulo equilatero";
            } else if ((base != altura) && (base != hipotenusa) && (altura != hipotenusa)){
                tipoTriangulo="Es un triangulo escaleno";
            } else {
                tipoTriangulo="Es un triangulo isósceles";
            }
            
            mensaje="Datos introducidos correctamente";
            mensajeAns.setText(mensaje);
            trianguloRectanguloTextPane.setText("area: "+area+"\n"+"perimetro: "+perimetro+"\n"+"hipotenusa: "+hipotenusa+"\n"+"tipo: "+tipoTriangulo);
        }
        catch(Exception e){
            mensaje="Entradas no válidas"+e;
            mensajeAns.setText(mensaje);
        }
    }                                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figuras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextPane CuadradoTextPane;
    private javax.swing.JTextField alturaInput;
    private javax.swing.JTextField alturaInput1;
    private javax.swing.JLabel alturaLabel;
    private javax.swing.JLabel alturaLabel1;
    private javax.swing.JTextField baseInput;
    private javax.swing.JTextField baseInput1;
    private javax.swing.JLabel baseLabel;
    private javax.swing.JLabel baseLabel1;
    private javax.swing.JPanel circuloAnsPanel;
    private javax.swing.JLabel circuloLabel;
    private javax.swing.JPanel circuloPanel;
    private javax.swing.JTextPane circuloTextPane;
    private javax.swing.JPanel cuadradoAnsPanel1;
    private javax.swing.JLabel cuadradoLabel1;
    private javax.swing.JPanel cuadradoPanel;
    private javax.swing.JButton enviarCirculo;
    private javax.swing.JButton enviarCuadrado;
    private javax.swing.JButton enviarRectangulo;
    private javax.swing.JButton enviarTrianguloRectangulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField ladoInput1;
    private javax.swing.JLabel ladoLabel1;
    private javax.swing.JLabel mensajeAns;
    private javax.swing.JTextField radioInput;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JPanel rectanguloAnsPanel;
    private javax.swing.JPanel rectanguloAnsPanel1;
    private javax.swing.JLabel rectanguloLabel;
    private javax.swing.JLabel rectanguloLabel1;
    private javax.swing.JPanel rectanguloPanel;
    private javax.swing.JPanel rectanguloPanel1;
    private javax.swing.JTextPane rectanguloTextPane;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextPane trianguloRectanguloTextPane;
    // End of variables declaration                   
}
