package Parte1;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;

/**
 *
 * @author sebastian
 */
public class Punto5_40 extends javax.swing.JFrame {

    /**
     * Creates new form Punto5_20
     */
    public Punto5_40() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        formulario = new javax.swing.JPanel();
        enviar = new javax.swing.JButton();
        theLabel = new javax.swing.JLabel();
        ourInput = new javax.swing.JTextField();
        avisito = new javax.swing.JLabel();
        mensajeAns = new javax.swing.JLabel();
        Respuesta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoRespuesta = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto3_20");
        setBackground(new java.awt.Color(249, 249, 249));
        setName("ventana"); // NOI18N

        titulo.setText("Punto 5.40");

        formulario.setBackground(new java.awt.Color(227, 227, 227));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        theLabel.setText("Grupo de numeros:");

        ourInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourInputActionPerformed(evt);
            }
        });

        avisito.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        avisito.setText("(Favor de colocarlos asi: \"1 3 4 5 ....\")");

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ourInput))
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formularioLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(mensajeAns, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formularioLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(theLabel))
                            .addGroup(formularioLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(avisito))
                            .addGroup(formularioLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(enviar)))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(theLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ourInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avisito)
                .addGap(18, 18, 18)
                .addComponent(enviar)
                .addGap(18, 18, 18)
                .addComponent(mensajeAns, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        Respuesta.setBackground(new java.awt.Color(210, 201, 201));

        jScrollPane1.setViewportView(textoRespuesta);

        javax.swing.GroupLayout RespuestaLayout = new javax.swing.GroupLayout(Respuesta);
        Respuesta.setLayout(RespuestaLayout);
        RespuestaLayout.setHorizontalGroup(
            RespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RespuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        RespuestaLayout.setVerticalGroup(
            RespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RespuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Respuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Respuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String mensaje,textAns="";
        String stringNumbers;
        double cuadrado,raiz,cubo,num;
        try{
            stringNumbers=ourInput.getText();
            mensaje="Datos introducidos correctamente";
            mensajeAns.setText(mensaje);

            List<String> numeros = new ArrayList<String>(Arrays.asList(stringNumbers.split(" ")));

            for (int i=0;i<numeros.size();i++) {
                num=Double.parseDouble(numeros.get(i)) ;
                cuadrado=Math.pow(num, 2);
                raiz=Math.sqrt(num);
                cubo=Math.pow(num, 3);
                textAns=textAns+"Del numero: "+num+"\n"+"Con cuadrado: "+cuadrado+"\n"+"Con raiz: "+raiz+"\n"+"Con cubo: "+cubo+"\n ----- \n";
            }
            textoRespuesta.setText(textAns);
        }
        catch(Exception e){
            mensaje="Entradas no válidas"+e;
            mensajeAns.setText(mensaje);
        }
    }                                      

    private void ourInputActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punto5_40.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punto5_40.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punto5_40.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punto5_40.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punto5_40().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Respuesta;
    private javax.swing.JLabel avisito;
    private javax.swing.JButton enviar;
    private javax.swing.JPanel formulario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensajeAns;
    private javax.swing.JTextField ourInput;
    private javax.swing.JTextPane textoRespuesta;
    private javax.swing.JLabel theLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration                   
}
